# Generated by Django 5.0 on 2023-12-08 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_alter_book_book_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='id',
        ),
        migrations.RemoveField(
            model_name='book',
            name='student',
        ),
        migrations.AlterField(
            model_name='book',
            name='book_name',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_no',
            field=models.IntegerField(unique=True),
        ),
        migrations.CreateModel(
            name='BookManage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateTimeField()),
                ('submit_date', models.DateTimeField(null=True)),
                ('book_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.book')),
                ('student', models.ManyToManyField(to='myApp.student')),
            ],
        ),
    ]
