# Generated by Django 5.0 on 2023-12-08 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_alter_book_book_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmanage',
            name='submit_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
