# Generated by Django 5.0 on 2023-12-08 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_alter_bookmanage_submit_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='studentclass',
            new_name='student_class',
        ),
    ]
